#!/usr/bin/env python3
"""Compute KL divergence between two bounded (clamped) Gaussian u-noise models.

We model the full control trajectory as a stacked vector u in R^{T*d}.

Base noise per element is Gaussian, then we apply element-wise clamp:
    y = clip(x, low, high)

This creates a mixed distribution (continuous on (low, high) plus point masses
at the bounds). Under the i.i.d. assumption across elements, KL for the full
trajectory factorizes:
    KL_total = (T*d) * KL_1d

We report:
- numeric KL for the 1D clamped distribution (Gauss-Legendre quadrature)
- optional Monte-Carlo estimate averaged over many seeds

No robot dependencies.
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass

import numpy as np


def _erf(z: np.ndarray) -> np.ndarray:
    """Error function with fallback for NumPy builds without np.erf."""
    z = np.asarray(z, dtype=np.float64)
    erf_np = getattr(np, "erf", None)
    if erf_np is not None:
        return erf_np(z)
    # Fallback: vectorize math.erf (works for scalars and arrays)
    return np.vectorize(math.erf, otypes=[np.float64])(z)


@dataclass(frozen=True)
class ClampedNormal1D:
    mu: float
    sigma: float
    low: float
    high: float


def _phi(z: np.ndarray) -> np.ndarray:
    return np.exp(-0.5 * z * z) / math.sqrt(2.0 * math.pi)


def _Phi(z: np.ndarray) -> np.ndarray:
    return 0.5 * (1.0 + _erf(z / math.sqrt(2.0)))


def _log_normal_pdf(x: np.ndarray, mu: float, sigma: float) -> np.ndarray:
    z = (x - mu) / sigma
    return -0.5 * z * z - math.log(sigma) - 0.5 * math.log(2.0 * math.pi)


def _clamp_masses(model: ClampedNormal1D) -> tuple[float, float]:
    a = model.low
    b = model.high
    alpha = (a - model.mu) / model.sigma
    beta = (b - model.mu) / model.sigma
    p_low = float(_Phi(np.asarray(alpha)))
    p_high = float(1.0 - _Phi(np.asarray(beta)))
    # numerical safety
    p_low = float(np.clip(p_low, 0.0, 1.0))
    p_high = float(np.clip(p_high, 0.0, 1.0))
    return p_low, p_high


def kl_clamped_normal_1d(p: ClampedNormal1D, q: ClampedNormal1D, quad_n: int = 512) -> float:
    """KL(P||Q) for 1D clamped normals (mixed discrete/continuous).

    P is generated by x~N(mu_p,sigma_p^2), y=clip(x,[low,high]); similarly Q.
    """
    if not (p.low < p.high and q.low < q.high):
        raise ValueError("invalid clamp bounds")
    if (p.low, p.high) != (q.low, q.high):
        raise ValueError("P and Q must share the same clamp bounds for this KL")
    if p.sigma <= 0.0 or q.sigma <= 0.0:
        raise ValueError("sigma must be positive")

    a = p.low
    b = p.high

    p_low, p_high = _clamp_masses(p)
    q_low, q_high = _clamp_masses(q)

    eps = 1e-300
    kl = 0.0
    if p_low > 0.0:
        kl += p_low * math.log(p_low / max(q_low, eps))
    if p_high > 0.0:
        kl += p_high * math.log(p_high / max(q_high, eps))

    # Continuous part: integral_a^b p(x) log(p(x)/q(x)) dx, where p(x),q(x) are *unclipped* PDFs.
    xs, ws = np.polynomial.legendre.leggauss(int(quad_n))
    x = 0.5 * (b - a) * xs + 0.5 * (b + a)
    w = 0.5 * (b - a) * ws

    p_pdf = _phi((x - p.mu) / p.sigma) / p.sigma
    log_ratio = _log_normal_pdf(x, p.mu, p.sigma) - _log_normal_pdf(x, q.mu, q.sigma)
    kl += float(np.sum(w * p_pdf * log_ratio))

    return float(kl)


def logpdf_clamped_vector(x: np.ndarray, model: ClampedNormal1D) -> np.ndarray:
    """Log probability of clamped model for vector samples.

    x: (n,k) values assumed already clamped into [low,high].
    Returns: (n,) log-prob.
    """
    low = model.low
    high = model.high
    p_low, p_high = _clamp_masses(model)
    log_p_low = -math.inf if p_low == 0.0 else math.log(p_low)
    log_p_high = -math.inf if p_high == 0.0 else math.log(p_high)

    tol = 1e-12
    at_low = x <= (low + tol)
    at_high = x >= (high - tol)
    inside = ~(at_low | at_high)

    logp = np.zeros_like(x, dtype=np.float64)
    if np.any(inside):
        logp[inside] = _log_normal_pdf(x[inside], model.mu, model.sigma)
    if np.any(at_low):
        logp[at_low] = log_p_low
    if np.any(at_high):
        logp[at_high] = log_p_high

    return np.sum(logp, axis=1)


def mc_kl_clamped(p: ClampedNormal1D, q: ClampedNormal1D, k: int, n: int, seed: int) -> float:
    rng = np.random.default_rng(seed)
    x = rng.normal(loc=p.mu, scale=p.sigma, size=(n, k)).astype(np.float64)
    x = np.clip(x, p.low, p.high)
    return float(np.mean(logpdf_clamped_vector(x, p) - logpdf_clamped_vector(x, q)))


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="KL divergence between u-trajectory Gaussian noises")
    ap.add_argument("--T", type=int, default=15, help="prediction horizon length")
    ap.add_argument("--dim", type=int, default=12, help="control dimension per step")
    ap.add_argument(
        "--std-a",
        type=float,
        nargs="+",
        default=[1.732050808, 1.414213562, 1.0, 0.781],
        help="std for model A (one or more values, e.g. --std-a 3.0 2.0 1.0)",
    )
    ap.add_argument("--std-b", type=float, default=0.774596669, help="std for model B")
    ap.add_argument("--mean-a", type=float, default=0.0, help="shared scalar mean for A (expanded)")
    ap.add_argument("--mean-b", type=float, default=0.0, help="shared scalar mean for B (expanded)")
    ap.add_argument("--clip-low", type=float, default=-2.0, help="Clamp lower bound (default -2)")
    ap.add_argument("--clip-high", type=float, default=2.0, help="Clamp upper bound (default 2)")
    ap.add_argument("--quad-n", type=int, default=512, help="Quadrature points for 1D KL (default 512)")
    ap.add_argument(
        "--mc",
        type=int,
        default=1,
        help="Monte Carlo sample count per seed (0 disables). Default=1.",
    )
    ap.add_argument(
        "--mc-seeds",
        type=int,
        default=1000,
        help="Number of different seeds to average (MC only). Default=1000.",
    )
    ap.add_argument("--seed", type=int, default=0, help="Base RNG seed (MC only)")
    return ap


def main() -> None:
    args = build_parser().parse_args()
    if args.T <= 0 or args.dim <= 0:
        raise SystemExit("T and dim must be positive")
    if any(s <= 0.0 for s in args.std_a) or args.std_b <= 0.0:
        raise SystemExit("std must be positive")
    if not (args.clip_low < args.clip_high):
        raise SystemExit("clip bounds must satisfy clip-low < clip-high")
    if args.quad_n <= 0:
        raise SystemExit("--quad-n must be positive")

    k = int(args.T * args.dim)
    b = ClampedNormal1D(mu=float(args.mean_b), sigma=float(args.std_b), low=float(args.clip_low), high=float(args.clip_high))

    print(f"T={args.T} dim={args.dim} (k={k})")
    print(f"bounds: [{args.clip_low}, {args.clip_high}]")
    print(f"B: std={args.std_b} mean={args.mean_b}")

    for std_a in args.std_a:
        a = ClampedNormal1D(mu=float(args.mean_a), sigma=float(std_a), low=float(args.clip_low), high=float(args.clip_high))

        kl1_a_b = kl_clamped_normal_1d(a, b, quad_n=int(args.quad_n))
        kl1_b_a = kl_clamped_normal_1d(b, a, quad_n=int(args.quad_n))
        kl_a_b = float(k) * kl1_a_b
        kl_b_a = float(k) * kl1_b_a

        print(f"A: std={std_a} mean={args.mean_a}")
        print(f"  KL_clamped(A||B) = {kl_a_b:.6f}")
        print(f"  KL_clamped(B||A) = {kl_b_a:.6f}")

        if args.mc and args.mc > 0:
            seeds_n = int(args.mc_seeds)
            if seeds_n <= 0:
                raise SystemExit("--mc-seeds must be positive")

            ests_a_b = np.empty((seeds_n,), dtype=np.float64)
            ests_b_a = np.empty((seeds_n,), dtype=np.float64)
            base = int(args.seed)
            for i in range(seeds_n):
                # use different seeds for each independent estimate
                ests_a_b[i] = mc_kl_clamped(a, b, k=k, n=int(args.mc), seed=base + 2 * i)
                ests_b_a[i] = mc_kl_clamped(b, a, k=k, n=int(args.mc), seed=base + 2 * i + 1)

            mean_a_b = float(np.mean(ests_a_b))
            std_a_b = float(np.std(ests_a_b, ddof=1)) if seeds_n > 1 else 0.0
            mean_b_a = float(np.mean(ests_b_a))
            std_b_a = float(np.std(ests_b_a, ddof=1)) if seeds_n > 1 else 0.0

            print(f"  MC  KL_clamped(A||B) ~ {mean_a_b:.6f} +/- {std_a_b:.6f} (seeds={seeds_n}, n/seed={args.mc})")
            print(f"  MC  KL_clamped(B||A) ~ {mean_b_a:.6f} +/- {std_b_a:.6f} (seeds={seeds_n}, n/seed={args.mc})")
        print("")


if __name__ == "__main__":
    main()
