ros_node_name: 'my_ros_node'
ros_update_rate: 125

# robot1 parameters
robot1_q_num: 6
robot1_q_name_list: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
robot1_q_sub_topic: 'ur3_joint_states'
robot1_dq_pub_topic: 'ur3_joint_command'
robot1_dh_type: 0 # 0 for standard DH parameters, 1 for modified DH parameters
robot1_dh_parameters:
  - [0.0, 0.1519, 0.0, 1.5708, 0]
  - [0.0, 0.0, -0.24365, 0.0, 0]
  - [0.0, 0.0, -0.21325, 0.0, 0]
  - [0.0, 0.11235, 0.0, 1.5708, 0]
  - [0.0, 0.08535, 0.0, -1.5708, 0]
  - [0.0, 0.0819, 0.0, 0.0, 0]
robot1_base: [0.612384, 0.353533, -0.353533, 0.612384, -0.087881, 0.013986, 0.013986, 0.087881]
robot1_effector: [1, 0, 0, 0, 0, 0, 0, 0]
# robot2 parameters
robot2_q_num: 6
robot2_q_name_list: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
robot2_q_sub_topic: 'ur3e_joint_states'
robot2_dq_pub_topic: 'ur3e_joint_command'
robot2_dh_type: 0
robot2_dh_parameters:
  - [0.0, 0.15185, 0.0, 1.5708, 0]
  - [0.0, 0.0, -0.24355, 0.0, 0]
  - [0.0, 0.0, -0.2132, 0.0, 0]
  - [0.0, 0.13105, 0.0, 1.5708, 0]
  - [0.0, 0.08535, 0.0, -1.5708, 0]
  - [0.0, 0.0921, 0.0, 0.0, 0]
robot2_base: [-0.612384, 0.353533, -0.353533, -0.612384, 0.087864, 0.013983, 0.013983, -0.087864]
robot2_effector: [1, 0, 0, 0, 0, 0, 0, 0]
high_level_u_topic: '/high_level_u'
curobo_world_file: 'ur_p2p_exp1_env.yml'
curobo_robot_file: 'dual_arm_model_real.yml'
# MPPI parameters
mppi_dt: 0.15
mppi_T: 15
mppi_seed: 0
batch_size: 1000
mean: 0.0
std: 3.0
an_std: 0.3
log_std: 0.0
max_acc_abs_value: 3.0
min_collision_distance: 0.00
min_self_collision_distance: 0.0
max_abs_tilt_angle: 8.0 
# Strict penalty weights
collision_constraint_weight: 1000.0
q_limit_constraint_weight: 0
q_vel_constraint_weight: 0
tilt_constraint_weight: 1000.0
# Mild penalty weights
abs_weight: 0.0
abs_position_weight: 0.0
q_acc_weight: 0.0
q_vel_weight: 0.0
stagnation_weight: 10.0
terminal_abs_weight: 100.0
terminal_abs_position_weight: 10.0
# high-level tradtition control parameters
high_rel_gain: 1.0
high_abs_gain: 2.0
# tradtition control parameters
rel_gain: 1.0
abs_gain: 1.0
# function c to change conrtoller
c_abs_max: 0.4
c_eta: 0.35
# joint position limits
robot1_q_min: [-6.0, -6.0, -6.0, -6.0, -6.0, -6.0]
robot1_q_max: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0]
robot2_q_min: [-6.0, -6.0, -6.0, -6.0, -6.0, -6.0]
robot2_q_max: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0]
# joint velocity limits
robot1_dq_min: [-0.8, -0.8, -0.8, -0.8, -0.8, -0.8]
robot1_dq_max: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
robot2_dq_min: [-0.8, -0.8, -0.8, -0.8, -0.8, -0.8]
robot2_dq_max: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
# joint velocity limits
robot1_ddq_min: [-2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
robot1_ddq_max: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
robot2_ddq_min: [-2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
robot2_ddq_max: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
